apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis-new
spec:
  containers:
  - image: redis
    name: redis-new
    resources: {}
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - HDD
