apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvtest
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/sahil/Documents/cka/getting-started-app"