apiVersion: v1
kind: ReplicationController
# RC metadata
metadata:
  name: nginxrc
  labels:
    app: demo
# POD metadata
spec:
  replicas: 3
  selector:     # Corrected: Added selector field. Replicationcontroller uses this
    app: nginxdemo
  template:     # Corrected: Moved template directly under spec
    metadata:
      labels:
        app: nginxdemo
  # Container metadata
    spec:
      containers:
        - name: nginxcontainer
          image: nginx