apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    env:
    # name Reference for container
    - name: FIRSTNAME
      valueFrom:
        configMapKeyRef:
            # name Reference of the actual cfg map & key used in it
          name: appcfgmap
          key: firstname
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']